# Generated by Django 3.0 on 2019-12-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador', models.CharField(max_length=200)),
                ('placa_mae', models.CharField(max_length=200)),
                ('menoria_ram', models.CharField(max_length=200)),
                ('placa_video', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
