# Generated by Django 3.0 on 2019-12-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191214_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('qtd_slots_memoria_ram', models.IntegerField()),
                ('total_memoria_ram_suportada', models.IntegerField()),
                ('video_integrado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='computador',
            name='processador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Processador'),
        ),
    ]
