# Generated by Django 3.0 on 2019-12-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191215_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='placa_mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PlacaMae'),
        ),
    ]
